# Generated by Django 5.2.7 on 2025-11-07 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authenticateduser',
            name='is_verifier',
            field=models.BooleanField(default=False),
        ),
    ]
