# Generated by Django 5.2.7 on 2025-11-30 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_authenticateduser_is_verifier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchhistory',
            name='user',
        ),
        migrations.RemoveField(
            model_name='sessionlog',
            name='user',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='SearchHistory',
        ),
        migrations.DeleteModel(
            name='SessionLog',
        ),
    ]
