# Generated by Django 5.2.7 on 2025-11-30 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_searchhistory_user_remove_sessionlog_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='charge',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
