# Generated by Django 5.2.7 on 2025-11-30 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_worker_charge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='charge',
        ),
    ]
