# Generated by Django 5.2.7 on 2025-11-30 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_worker_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerapplication',
            name='base_charge',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workerapplication',
            name='selected_service_category',
            field=models.CharField(blank=True, help_text='Service category selected for this worker after approval', max_length=100, null=True),
        ),
    ]
