# Generated by Django 5.2.7 on 2025-11-30 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_workerapplication_base_charge_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='application',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.workerapplication'),
        ),
    ]
