# Generated by Django 5.2.7 on 2025-11-30 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_worker_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerapplication',
            name='selected_service_category',
            field=models.CharField(blank=True, choices=[('painter', 'Painter'), ('plumber', 'Plumber'), ('electrician', 'Electrician'), ('gardener', 'Gardener'), ('cleaner', 'Cleaner'), ('carpenter', 'Carpenter'), ('mason', 'Mason')], help_text='Service category selected for this worker after approval', max_length=100, null=True),
        ),
    ]
