# Generated by Django 5.2.5 on 2025-10-03 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_userworkerdata_worker_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerearning',
            name='user_review',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='worker_earning', to='core.userreview'),
        ),
    ]
